### .dein.toml
#
# if in trouble,
# 1). sudo apt-get update neovim ; correct?
# 2). pip install --upgrade neovim
# 3). (on vim) :UpdateRemotePlugins,:checkhealth,:call dein#update()
#

[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'easymotion/vim-easymotion'
hook_add = '''
  let g:EasyMotion_smartcase = 1
'''

[[plugins]]
repo = 'qpkorr/vim-bufkill'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'tpope/vim-repeat'

[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'jistr/vim-nerdtree-tabs'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'airblade/vim-gitgutter'
hook_add = '''
  let g:gitgutter_override_sign_column_highlight = 0
  highlight clear SignColumn
  highlight SignColumn ctermbg=gray
  highlight GitGutterAdd ctermfg=green ctermbg=235
  highlight GitGutterChange ctermfg=cyan ctermbg=235
  highlight GitGutterDelete ctermfg=red ctermbg=235
  highlight GitGutterChangeDelete ctermfg=cyan ctermbg=235
'''

[[plugins]]
repo = 'tpope/vim-obsession'

[[plugins]]
repo = 'junegunn/fzf'
build = './install --all'
merged = '0'

[[plugins]]
repo = 'junegunn/fzf.vim'
depends = 'fzf'
hook_source = '''
  let g:fzf_tags_command = 'ctags -R -f .tags'
  command! -bang -nargs=* Ag call
    \ fzf#vim#ag(<q-args>,{'options': '--delimiter : --nth 4..'},<bang>0)
  command! -bang -nargs=* Files call
    \ fzf#vim#files(<q-args>,
    \            <bang>0 ? fzf#vim#with_preview('up:60%')
    \                    : fzf#vim#with_preview('right:50%:hidden', '?'),
    \            <bang>0)
'''

[[plugins]]
repo = 'simnalamburt/vim-mundo'
hook_source = '''
  let g:mundo_preview_bottom = 1
  let g:mundo_width = 35
  let g:mundo_preview_statusline = '[Undotree-preview]'
  let g:mundo_tree_statusline  = '[Undotree]'
'''

[[plugins]]
repo = 'Yggdroot/indentLine'
hook_source = '''
  let g:indentLine_enabled = 1
  let g:indentLine_fileType = ['c','sh','php','smarty','python','ruby']
  let g:indentLine_char = '¦'
  let g:indentLine_first_char = '¦'
'''

[[plugins]]
repo = 'majutsushi/tagbar'
hook_source = '''
  let g:tagbar_autofocus = 1
'''

[[plugins]]
repo = 'w0rp/ale'
hook_add = '''
  nmap <silent> <C-p> <Plug>(ale_previous_wrap)
  nmap <silent> <C-n> <Plug>(ale_next_wrap)
  highlight ALEWarning ctermbg=Darkgray ctermfg=yellow
  highlight ALEError ctermbg=Darkgray ctermfg=red
  let g:ale_lint_on_text_changed = 'normal'
  let g:ale_lint_on_insert_leave = 1
  let g:ale_echo_msg_format = '[%linter%]%s [%severity%]'
  function! LinterStatus() abort
    let l:counts = ale#statusline#Count(bufnr(''))
    let l:all_errors = l:counts.error + l:counts.style_error
    let l:all_non_errors = l:counts.total - l:all_errors
    return l:counts.total == 0 ? '' : printf(
    \   '%dW %dE',
    \   all_non_errors,
    \   all_errors
    \)
  endfunction
'''

[[plugins]]
repo = 'thinca/vim-ref'
hook_add = '''
  let g:ref_use_vimproc = 1
  let g:ref_phpmanual_path = '/home/naoki/usr/doc/ref/php-chunked-xhtml'
'''
