### .dein.toml
#
# if in trouble,
# 1). sudo apt-get update neovim ; correct?
# 2). pip install --upgrade neovim
# 3). (on vim) :UpdateRemotePlugins,:checkhealth,:call dein#update()
#

[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/denite.nvim'
hook_post_source = '''
  call denite#custom#var('file_rec', 'command', ['ag', '--follow', '--nocolor', '--nogroup', '-g', ''])
  call denite#custom#var('grep', 'command', ['ag'])
  call denite#custom#var('grep', 'default_opts', ['--follow', '--no-group', '--no-color'])
'''

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'jistr/vim-nerdtree-tabs'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'tpope/vim-fugitive'

# when loaded with fugitive & statusline of it enabled, error on loading occurs.
[[plugins]]
repo = 'tpope/vim-obsession'
