### .dein.toml
#
# if in trouble,
# 1). sudo apt-get update neovim ; correct?
# 2). pip install --upgrade neovim
# 3). (on vim) :UpdateRemotePlugins,:checkhealth,:call dein#update()
#

[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'jistr/vim-nerdtree-tabs'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'tpope/vim-obsession'

[[plugins]]
repo = 'junegunn/fzf'
build = './install --all'
merged = '0'

[[plugins]]
repo = 'junegunn/fzf.vim'
depends = 'fzf'
hook_source = '''
  let g:fzf_tags_command = 'ctags -R -f .tags'
  command! -bang -nargs=* Ag call
    \ fzf#vim#ag(<q-args>,{'options': '--delimiter : --nth 4..'},<bang>0)
  command! -bang -nargs=* Files call
    \ fzf#vim#files(<q-args>,
    \            <bang>0 ? fzf#vim#with_preview('up:60%')
    \                    : fzf#vim#with_preview('right:50%:hidden', '?'),
    \            <bang>0)
'''
#TODO;Ag - need both "1.filename ignore" & "2.preview" as its feature.

[[plugins]]
repo = 'simnalamburt/vim-mundo'
hook_source = '''
  let g:mundo_preview_bottom = 1
  let g:mundo_width = 35
  let g:mundo_preview_statusline = '[Undotree-preview]'
  let g:mundo_tree_statusline  = '[Undotree]'
'''

[[plugins]]
repo = 'Yggdroot/indentLine'
hook_source = '''
  let g:indentLine_enabled = 1
  let g:indentLine_fileType = ['c','sh','php','smarty','python','ruby']
  let g:indentLine_char = '¦'
  let g:indentLine_first_char = '¦'
  let g:indentLine_showFirstIndentLevel = 1
'''

[[plugins]]
repo = 'thinca/vim-ref'
hook_source = '''
  let g:ref_use_vimproc = 1
  let g:ref_phpmanual_path = '/home/naoki/usr/doc/dict/php-chunked-xhtml'
'''
#TODO:phpmanual "often" not available.
