### .dein_lazy.toml

[[plugins]]
repo = 'thinca/vim-quickrun'
hook_add = '''
  let g:quickrun_config = {
  \ "runner" : "vimproc",
  \	"_" : {
  \  "outputter/buffer/split" : ":botright",
  \  "outputter/error/success" : "buffer",
  \  "outputter/error/error/" : "quickfix",
  \  "outputter/buffer/into" : "1",
  \  "outputter/quickfix/errorformat" : "%f:%l,%m in %f on line %l",
  \  "outputter/buffer/close_on_empty" : 1,
  \  "outputter" : "error"
  \  }
  \}
  let g:quickrun_no_default_key_mappings = 1
  nnoremap \r :QuickRun -mode n<CR>
  xnoremap \r :QuickRun -mode v<CR>
  nnoremap <expr><silent> <C-c> quickrun#is_running() ? quickrun#sweep_sessions() : "\<C-c>"
  au FileType qf nnoremap <silent><buffer>q :quit<CR>
'''

[[plugins]]
repo = 'cohama/lexima.vim'
on_ft = [ 'python', 'sh', 'c', 'php', 'ruby' ]

## Good one. But Not now.
#[[plugins]]
#repo = 'davidhalter/jedi-vim'
#on_ft = 'python'
#hook_add = '''
#	autocmd FileType python setl smartindent cinwords=if,elif,else,for,while,try,except,finally,def,class
#	autocmd FileType python setlocal completeopt-=preview
#	let g:jedi#rename_command = "<leader>v"
#    let g:jedi#completions_command = "<C-n>"
#	let g:jedi#popup_on_dot=0
#	let g:jedi#smart_auto_mappings = 0
#'''

[[plugins]]
repo = 'Shougo/deoplete.nvim'
hook_source = '''
  let g:deoplete#enable_at_startup = 1
  imap <expr><C-l>
  \ neosnippet#expandable() <Bar><Bar> neosnippet#jumpable() ?
  \ "\<Plug>(neosnippet_expand_or_jump)" : "\<C-n>"
'''
on_event = 'InsertCharPre'

[[plugins]]
repo = 'Shougo/neosnippet'
hook_source = '''
  imap <C-l> <Plug>(neosnippet_expand_or_jump)
  smap <C-l> <Plug>(neosnippet_expand_or_jump)
  xmap <C-l> <Plug>(neosnippet_expand_target)
  if has('conceal')
    set conceallevel=2 concealcursor=niv
  endif
  let g:neosnippet#snippets_directory='~/usr/doc/snippets/'
'''
on_event = 'InsertCharPre'
on_ft = ['snippet']
depends = ['neosnippet-snippets']
